[package]
name = "shaco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.23.5"
regex = "1.5.5"
lazy_static = "1.4.0"
base64 = "0.13.0"
serde_json = "1.0.79"

[dependencies.reqwest]
version = "0.11.10"
features = ["json"]

[dev-dependencies.tokio]
version = "1"
features = ["full"] 