[package]
name = "shaco"
version = "0.2.1"
edition = "2021"
description = "A League of Legends wrapper for the LCU REST and the ingame API"
license = "MIT"
documentation = "https://docs.rs/shaco"
readme = "README.md"
homepage = "https://github.com/Leastrio/Shaco"
repository = "https://github.com/Leastrio/Shaco"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.23.5"
regex = "1.5.5"
lazy_static = "1.4.0"
base64 = "0.13.0"
serde_json = "1.0.79"
# wamp_async = "0.3.1"

[dependencies.reqwest]
version = "0.11.10"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies.tokio]
version = "1"
features = ["full"]